# Generated by Django 3.1.6 on 2021-02-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PollMaker', '0002_remove_pollquestion_can_make_own_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='can_make_own_answer',
            field=models.BooleanField(default=False),
        ),
    ]
